Xidea\Bundle\UserBundle\Entity\AbstractUser:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255
        salt:
            type: string
            length: 32