parameters:
    xidea_user.configuration.default.class: Xidea\Bundle\BaseBundle\Configuration
    xidea_user.template_configuration.default.class: Xidea\Bundle\BaseBundle\TemplateConfiguration
  
services:
    xidea_user.configuration.default:
        class: %xidea_user.configuration.default.class%
        arguments:
            - @xidea_user.template_configuration
    xidea_user.template_configuration.default:
        class: %xidea_user.template_configuration.default.class%
        arguments:
            - %xidea_user.template.namespace%
            - %xidea_user.template.templates%
            - %xidea_user.template.engine%