parameters:
    xidea_user.controller.change_password.class: Xidea\Bundle\UserBundle\Controller\User\ChangePasswordController

services:
    xidea_user.controller.change_password:
        class: %xidea_user.controller.change_password.class%
        arguments:
            - @security.context
            - @xidea_user.user_manager
            - @xidea_user.change_password.form.factory
            - @router
            - @event_dispatcher
            - @templating
            - @translator
    xidea_user.change_password.form.factory:
        class: Xidea\Bundle\UserBundle\Form\Factory\FormFactory
        arguments:
            - @form.factory
            - %xidea_user.change_password.form.name%
            - %xidea_user.change_password.form.type%
            - %xidea_user.change_password.form.validation_groups%
    xidea_user.change_password.form.type:
        class: Xidea\Bundle\UserBundle\Form\Type\ChangePasswordType
        arguments:
            - %xidea_user.user.class%
        tags:
            - { name: form.type, alias: "xidea_user_change_password" }