parameters:
    xidea_user.controller.list.class: Xidea\Bundle\UserBundle\Controller\User\ListController
    xidea_user.controller.show.class: Xidea\Bundle\UserBundle\Controller\User\ShowController
    xidea_user.controller.create.class: Xidea\Bundle\UserBundle\Controller\User\CreateController
  
services:
    xidea_user.controller.list:
        class: %xidea_user.controller.list.class%
        arguments:
            - @xidea_user.configuration
            - @xidea_user.user.loader
        calls:
            - [setEventDispatcher, [@event_dispatcher]]
            - [setTemplating, [@templating]]
    xidea_user.controller.show:
        class: %xidea_user.controller.show.class%
        arguments:
            - @xidea_user.configuration
            - @xidea_user.user.loader
        calls:
            - [setEventDispatcher, [@event_dispatcher]]
            - [setTemplating, [@templating]]
    xidea_user.controller.create:
        class: %xidea_user.controller.create.class%
        arguments:
            - @xidea_user.configuration
            - @xidea_user.user.director
            - @xidea_user.user.manager
            - @xidea_user.user.form.create.handler
        calls:
            - [setEventDispatcher, [@event_dispatcher]]
            - [setRouter, [@router]]
            - [setTemplating, [@templating]]