parameters:
    xidea_user.controller.create.class: Xidea\Bundle\UserBundle\Controller\User\CreateController
  
services:
    xidea_user.controller.create:
        class: %xidea_user.controller.create.class%
        arguments:
            - @xidea_user.user_director
            - @xidea_user.user_manager
            - @xidea_user.user_create.form.handler
            - @event_dispatcher
            - @router
            - @templating