parameters:
    xidea_user.controller.create.class: Xidea\Bundle\UserBundle\Controller\Ticket\CreateController
  
services:
    xidea_user.controller.create:
        class: %xidea_user.controller.create.class%
        arguments:
            - @xidea_user.user_director
            - @xidea_user.user_manager
            - @xidea_user.create_form.handler
            - @event_dispatcher
            - @xidea_user.url_manager
            - @xidea_user.template_manager