services:
    xidea_user.user_create.form.type:
        class: Xidea\Bundle\UserBundle\Form\Type\CreateType
        arguments:
            - %xidea_user.user.class%
        tags:
            - { name: form.type, alias: "xidea_user_create" }
    xidea_user.user_create.form.factory:
        class: Xidea\Bundle\UserBundle\Form\Factory\FormFactory
        arguments:
            - @form.factory
            - %xidea_user.user_create.form.name%
            - %xidea_user.user_create.form.type%
            - %xidea_user.user_create.form.validation_groups%
    xidea_user.user_create.form.handler:
        class: Xidea\Bundle\UserBundle\Form\Handler\UserFormHandler
        arguments:
            - @xidea_user.user_create.form.factory
            - @event_dispatcher