parameters:
    xidea_user.profile.configuration.default.class: Xidea\Bundle\BaseBundle\Configuration
    xidea_user.profile.factory.default.class: Xidea\Component\Base\Factory\ModelFactory
  
services:
    xidea_user.profile.configuration.default:
        class: %xidea_user.profile.configuration.default.class%
        arguments:
            - %xidea_user.profile.code%
            - @xidea_user.template.configuration
        tags:
            - { name: xidea_base.configuration }
    xidea_user.profile.factory.default:
        class: %xidea_user.profile.factory.default.class%
        arguments:
            - %xidea_user.profile.class%