parameters:
    #services
    xidea_user.profile.configuration.default.class: Xidea\Bundle\BaseBundle\Configuration
    xidea_user.profile.factory.default.class: Xidea\Base\Model\Factory\DefaultFactory
    #controllers
    xidea_user.profile_controller.show.class: Xidea\Bundle\UserBundle\Controller\Profile\ShowController
  
services:
    #services
    xidea_user.profile.configuration.default:
        class: %xidea_user.profile.configuration.default.class%
        arguments:
            - %xidea_user.profile.code%
        tags:
            - { name: xidea_base.configuration }
    xidea_user.profile.factory.default:
        class: %xidea_user.profile.factory.default.class%
        arguments:
            - %xidea_user.profile.class%
    #controllers
    xidea_user.profile_controller.show:
        class: %xidea_user.profile_controller.show.class%
        arguments:
            - @xidea_user.profile.configuration
            - @xidea_user.user.loader
        calls:
            - [setEventDispatcher, [@event_dispatcher]]
            - [setTemplateManager, [@xidea_base.template_manager]]