parameters:
    xidea_user.profile_controller.show.class: Xidea\Bundle\UserBundle\Controller\Profile\ShowController
  
services:
    xidea_user.profile_controller.show:
        class: %xidea_user.profile_controller.show.class%
        arguments:
            - @xidea_user.profile.configuration
            - @xidea_user.user.loader
        calls:
            - [setEventDispatcher, [@event_dispatcher]]
            - [setTemplating, [@templating]]