parameters:
    xidea_user.controller.registration.class: Xidea\Bundle\UserBundle\Controller\User\RegistrationController

services:
    xidea_user.controller.registration:
        class: %xidea_user.controller.registration.class%
        arguments:
            - @xidea_user.user_factory
            - @xidea_user.user_manager
            - @xidea_user.registration.form.factory
            - @event_dispatcher
            - @templating
            - @translator
    xidea_user.registration.form.factory:
        class: Xidea\Bundle\UserBundle\Form\Factory\FormFactory
        arguments:
            - @form.factory
            - %xidea_user.registration.form.name%
            - %xidea_user.registration.form.type%
            - %xidea_user.registration.form.validation_groups%
    xidea_user.registration.form.type:
        class: Xidea\Bundle\UserBundle\Form\Type\RegistrationType
        arguments:
            - %xidea_user.user.class%
        tags:
            - { name: form.type, alias: "xidea_user_registration" }