parameters:
    xidea_user.user.configuration.default.class: Xidea\Bundle\BaseBundle\Configuration
    xidea_user.user.factory.default.class: Xidea\Base\Model\Factory\DefaultFactory
    xidea_user.user.builder.default.class: Xidea\User\Builder\DefaultBuilder
    xidea_user.user.director.default.class: Xidea\User\Builder\DefaultDirector
  
services:
    xidea_user.user.configuration.default:
        class: %xidea_user.user.configuration.default.class%
        arguments:
            - %xidea_user.user.code%
        tags:
            - { name: xidea_base.configuration }
    xidea_user.user.factory.default:
        class: %xidea_user.user.factory.default.class%
        arguments:
            - %xidea_user.user.class%
    xidea_user.user.builder.default:
        class: %xidea_user.user.builder.default.class%
        arguments:
            - @xidea_user.user.factory
    xidea_user.user.director.default:
        class: %xidea_user.user.director.default.class%
        arguments:
            - @xidea_user.user.builder