parameters:
    xidea_user.user.repository.default.class: Xidea\Bundle\UserBundle\Doctrine\ORM\Repository\UserRepository
    xidea_user.user.loader.default.class: Xidea\Bundle\UserBundle\Doctrine\ORM\Loader\UserLoader
    xidea_user.user.manager.default.class: Xidea\Bundle\UserBundle\Doctrine\ORM\Manager\UserManager
  
services:
    xidea_user.user.repository.default:
        class: '%xidea_user.user.repository.default.class%'
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - '%xidea_user.user.class%'
    xidea_user.user.loader.default:
        class: '%xidea_user.user.loader.default.class%'
        arguments:
            - '@xidea_user.user.repository.default'
            - '@xidea_user.user.configuration'
            - '@xidea_base.paginator'
    xidea_user.user.manager.default:
        class: '%xidea_user.user.manager.default.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.encoder_factory'
            - '@event_dispatcher'
