parameters:
    xidea_user.user.factory.default.class: Xidea\Component\User\Factory\UserFactory
    xidea_user.user.builder.default.class: Xidea\Component\User\Builder\UserBuilder
    xidea_user.user.director.default.class: Xidea\Component\User\Builder\UserDirector
  
services:
    xidea_user.user.factory.default:
        class: %xidea_user.user.factory.default.class%
        arguments:
            - %xidea_user.user.class%
    xidea_user.user.builder.default:
        class: %xidea_user.user.builder.default.class%
        arguments:
            - @xidea_user.user.factory
    xidea_user.user.director.default:
        class: %xidea_user.user.director.default.class%
        arguments:
            - @xidea_user.user.builder