Xidea\Component\User\Model\AbstractUser:
    type: mappedSuperclass
    repositoryClass: Xidea\Bundle\UserBundle\Doctrine\ORM\Repository\UserRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 255
            unique: true
        salt:
            type: string
            length: 32
        password:
            type: string
            length: 255