Xidea\User\AbstractUser:
    type: mappedSuperclass
    repositoryClass: Xidea\Bundle\UserBundle\Doctrine\ORM\Repository\UserRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 255
            unique: true
        salt:
            type: string
            length: 32
        password:
            type: string
            length: 255
    manyToMany:
        roles:
            targetEntity: Xidea\User\RoleInterface
            joinTable:
                name: user_role
                joinColumns:
                    user_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id
                        onDelete: CASCADE
            cascade: ["persist"]