Xidea\Bundle\UserBundle\Model\AbstractProfile:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
    oneToOne:
        user:
            targetEntity: Xidea\Bundle\UserBundle\Model\AbstractAdvancedUser
            mappedBy: profile