Xidea\Bundle\UserBundle\Model\AbstractAdvancedUser:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 255
            unique: true
        salt:
            type: string
            length: 32
        password:
            type: string
            length: 255
        email:
            type: string
            length: 128
            unique: true
        isEnabled:
            column: is_enabled
            type: boolean
        createdAt:
            column: created_at
            type: datetime
            nullable: true
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
        lastLogin:
            column: last_login
            type: datetime
            nullable: true
        confirmationToken:
            column: confirmation_token
            type: string
            length: 255
            nullable: true
    oneToOne:
        profile:
            targetEntity: Xidea\Bundle\UserBundle\Model\AbstractProfile
            inversedBy: user
            cascade: ["persist"]