Xidea\Bundle\UserBundle\Model\AbstractRole:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        role:
            type: string
            length: 128